### ISSUE TITLE
No downloadable version for aarch

### ISSUE THREAD

**Issue by bonzofenix** [lwiechec/asdf-gum#3]
**Describe the bug**

No downloadable version for aarch

see available releases artifacts: 
https://github.com/charmbracelet/gum/releases/tag/v0.11.0

**Screenshots**
<img width="1510" alt="Screenshot 2023-11-05 at 14 07 25" src="https://github.com/lwiechec/asdf-gum/assets/317403/204c6532-ca5c-44b2-8e52-ba13053a32dc">

**Comment by lwiechec** [comment]
@bonzofenix thanks for reporting. It looks like gum changed the way they package the artifacts in releases. I will get it working again.
PS: could you please tell me what do you see when you do `uname -m` ? `gum` removed `aarch64` and I think the best choice is to offer `arm64`

**Comment by michaelefisher** [comment]
Seeing this as well, and changing the case option to `arm64` did the trick, as this is what I get for `uname -m` on an M1 mac:
```
sh-3.2# uname -m
arm64
```

**Comment by lwiechec** [comment]
@michaelefisher thank you for helping out with M1.

I have created a branch that should download `gum` on M: https://github.com/lwiechec/asdf-gum/tree/fix-3-adding-uname-for-M1-mac - I wonder if you could test if it does?

**Comment by lwiechec** [comment]
...closing
